import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";

const poppinsSemiBold = Poppins({
  subsets: ["latin"],
  weight: '600'
});

const poppinsLight = Poppins({
  subsets: ["latin"],
  weight: '400'
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppinsLight.className} ${poppinsSemiBold.className} antialiased`}>
        <div className="p-2">
          <div className="grid h-11 p-2.5 rounded-md bg-gray-700">
            <a href="https://lemon-studios.ca">Lemon Studios</a>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
